spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false'
    username: 'user'
    password: ''
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: production
  sql:
    init:
      mode: never