spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinemadb
    username: 'cinema'
    password: 'cinema'
  jpa:
    database-platform: 'org.hibernate.dialect.MySQLDialect'
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.mail.com
    username: mail@mail.com
    password: password
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
logging:
  level:
    root: info
---

spring:
  config:
    activate:
      on-profile: production
  sql:
    init:
      mode: never
