openapi: "3.0.3"
info:
  title: "backend API"
  description: "backend API"
  version: "1.0.0"
servers:
  - url: "https://backend"
paths:
  /api/genre:
    post:
      summary: "POST api/genre"
      operationId: "addGenre"
      responses:
        "200":
          description: "OK"
  /api/genre/all:
    get:
      summary: "GET api/genre/all"
      operationId: "getAllGenres"
      responses:
        "200":
          description: "OK"
  /api/movie:
    post:
      summary: "POST api/movie"
      operationId: "addMovie"
      responses:
        "200":
          description: "OK"
  /api/movie/all:
    get:
      summary: "GET api/movie/all"
      operationId: "getAllMovies"
      responses:
        "200":
          description: "OK"
  /api/movie/{id}:
    get:
      summary: "GET api/movie/{id}"
      operationId: "getMovieById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        "200":
          description: "OK"
  /api/person:
    post:
      summary: "POST api/person"
      operationId: "addPerson"
      responses:
        "200":
          description: "OK"
  /api/person/all:
    get:
      summary: "GET api/person/all"
      operationId: "getAll"
      responses:
        "200":
          description: "OK"
  /api/person/{id}:
    get:
      summary: "GET api/person/{id}"
      operationId: "getById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        "200":
          description: "OK"
  /api/showtime:
    post:
      summary: "POST api/showtime"
      operationId: "add"
      responses:
        "200":
          description: "OK"
  /api/showtime/current:
    get:
      summary: "GET api/showtime/current"
      operationId: "getCurrent"
      responses:
        "200":
          description: "OK"
  /api/showtime/current-grouped:
    get:
      summary: "GET api/showtime/current-grouped"
      operationId: "getCurrentGrouped"
      responses:
        "200":
          description: "OK"
  /api/showtime/of-date-grouped/{dateStr}:
    get:
      summary: "GET api/showtime/of-date-grouped/{dateStr}"
      operationId: "getCurrentGrouped"
      parameters:
        - name: "dateStr"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
  /api/showtime/of-date/{dateStr}:
    get:
      summary: "GET api/showtime/of-date/{dateStr}"
      operationId: "getOfDate"
      parameters:
        - name: "dateStr"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
  /api/showtime/of-movie/{movieId}:
    get:
      summary: "GET api/showtime/of-movie/{movieId}"
      operationId: "getOfMovie"
      parameters:
        - name: "movieId"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        "200":
          description: "OK"
  /api/technology/all:
    get:
      summary: "GET api/technology/all"
      operationId: "getAllTechnologies"
      responses:
        "200":
          description: "OK"
  /api/technology/new:
    get:
      summary: "GET api/technology/new"
      operationId: "addTechnology"
      responses:
        "200":
          description: "OK"
  /login:
    post:
      summary: "POST login"
      operationId: "login"
      responses:
        "200":
          description: "OK"
  /register:
    post:
      summary: "POST register"
      operationId: "register"
      responses:
        "200":
          description: "OK"